services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
  db-migrator:
    image: db-migrator
    build:
      context: .
      dockerfile: DbMigrator/Dockerfile
      
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"

volumes:
    db-data: